[package]
name = "tl-codegen"
version = "0.1.0"
authors = ["Matteo Guarda <matteoguarda@tutanota.com>"]
edition = "2018"

[dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.19"
nom = "5.1.2"
regex = "1.3.9"
lazy_static = "1.4.0"
